# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QRadioButton, QSizePolicy, QSplitter,
    QStackedWidget, QStatusBar, QTextBrowser, QTreeWidget,
    QTreeWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(850, 550)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pages = QStackedWidget(self.centralwidget)
        self.pages.setObjectName(u"pages")
        self.pages.setGeometry(QRect(10, 50, 821, 451))
        self.page_inserir = QWidget()
        self.page_inserir.setObjectName(u"page_inserir")
        self.label_2 = QLabel(self.page_inserir)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(120, 0, 181, 51))
        font = QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_5 = QLabel(self.page_inserir)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(140, 130, 121, 51))
        self.label_5.setFont(font)
        self.splitter_4 = QSplitter(self.page_inserir)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setGeometry(QRect(20, 170, 381, 41))
        self.splitter_4.setOrientation(Qt.Vertical)
        self.label_6 = QLabel(self.splitter_4)
        self.label_6.setObjectName(u"label_6")
        self.splitter_4.addWidget(self.label_6)
        self.input_p_nome = QLineEdit(self.splitter_4)
        self.input_p_nome.setObjectName(u"input_p_nome")
        self.splitter_4.addWidget(self.input_p_nome)
        self.label_9 = QLabel(self.page_inserir)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 390, 261, 21))
        self.splitter_7 = QSplitter(self.page_inserir)
        self.splitter_7.setObjectName(u"splitter_7")
        self.splitter_7.setGeometry(QRect(20, 220, 141, 41))
        self.splitter_7.setOrientation(Qt.Vertical)
        self.label_10 = QLabel(self.splitter_7)
        self.label_10.setObjectName(u"label_10")
        self.splitter_7.addWidget(self.label_10)
        self.input_p_meses = QLineEdit(self.splitter_7)
        self.input_p_meses.setObjectName(u"input_p_meses")
        self.splitter_7.addWidget(self.input_p_meses)
        self.splitter_8 = QSplitter(self.page_inserir)
        self.splitter_8.setObjectName(u"splitter_8")
        self.splitter_8.setGeometry(QRect(250, 220, 151, 41))
        self.splitter_8.setOrientation(Qt.Vertical)
        self.label_11 = QLabel(self.splitter_8)
        self.label_11.setObjectName(u"label_11")
        self.splitter_8.addWidget(self.label_11)
        self.input_p_valor_est = QLineEdit(self.splitter_8)
        self.input_p_valor_est.setObjectName(u"input_p_valor_est")
        self.splitter_8.addWidget(self.input_p_valor_est)
        self.splitter_9 = QSplitter(self.page_inserir)
        self.splitter_9.setObjectName(u"splitter_9")
        self.splitter_9.setGeometry(QRect(20, 280, 141, 41))
        self.splitter_9.setOrientation(Qt.Vertical)
        self.label_12 = QLabel(self.splitter_9)
        self.label_12.setObjectName(u"label_12")
        self.splitter_9.addWidget(self.label_12)
        self.input_p_n_func = QLineEdit(self.splitter_9)
        self.input_p_n_func.setObjectName(u"input_p_n_func")
        self.splitter_9.addWidget(self.input_p_n_func)
        self.log_inserir = QTextBrowser(self.page_inserir)
        self.log_inserir.setObjectName(u"log_inserir")
        self.log_inserir.setGeometry(QRect(450, 40, 371, 401))
        self.label_13 = QLabel(self.page_inserir)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(450, 10, 141, 20))
        self.btn_inserir_f = QPushButton(self.page_inserir)
        self.btn_inserir_f.setObjectName(u"btn_inserir_f")
        self.btn_inserir_f.setGeometry(QRect(340, 110, 75, 23))
        self.btn_p_inserir = QPushButton(self.page_inserir)
        self.btn_p_inserir.setObjectName(u"btn_p_inserir")
        self.btn_p_inserir.setGeometry(QRect(330, 300, 75, 23))
        self.btn_limpar_p_inserir = QPushButton(self.page_inserir)
        self.btn_limpar_p_inserir.setObjectName(u"btn_limpar_p_inserir")
        self.btn_limpar_p_inserir.setGeometry(QRect(240, 300, 75, 23))
        self.btn_limpar_f_inserir = QPushButton(self.page_inserir)
        self.btn_limpar_f_inserir.setObjectName(u"btn_limpar_f_inserir")
        self.btn_limpar_f_inserir.setGeometry(QRect(340, 60, 75, 23))
        self.splitter = QSplitter(self.page_inserir)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(20, 40, 301, 41))
        self.splitter.setOrientation(Qt.Vertical)
        self.label_3 = QLabel(self.splitter)
        self.label_3.setObjectName(u"label_3")
        self.splitter.addWidget(self.label_3)
        self.input_f_nome = QLineEdit(self.splitter)
        self.input_f_nome.setObjectName(u"input_f_nome")
        self.splitter.addWidget(self.input_f_nome)
        self.splitter_2 = QSplitter(self.page_inserir)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(190, 90, 133, 41))
        self.splitter_2.setOrientation(Qt.Vertical)
        self.label_4 = QLabel(self.splitter_2)
        self.label_4.setObjectName(u"label_4")
        self.splitter_2.addWidget(self.label_4)
        self.input_f_salario = QLineEdit(self.splitter_2)
        self.input_f_salario.setObjectName(u"input_f_salario")
        self.splitter_2.addWidget(self.input_f_salario)
        self.splitter_3 = QSplitter(self.page_inserir)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setGeometry(QRect(20, 90, 141, 41))
        self.splitter_3.setOrientation(Qt.Vertical)
        self.label = QLabel(self.splitter_3)
        self.label.setObjectName(u"label")
        self.splitter_3.addWidget(self.label)
        self.input_f_n_func = QLineEdit(self.splitter_3)
        self.input_f_n_func.setObjectName(u"input_f_n_func")
        self.splitter_3.addWidget(self.input_f_n_func)
        self.splitter_5 = QSplitter(self.page_inserir)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setGeometry(QRect(20, 370, 231, 20))
        self.splitter_5.setMinimumSize(QSize(0, 20))
        self.splitter_5.setOrientation(Qt.Horizontal)
        self.label_8 = QLabel(self.splitter_5)
        self.label_8.setObjectName(u"label_8")
        self.splitter_5.addWidget(self.label_8)
        self.data_p_termino = QDateEdit(self.splitter_5)
        self.data_p_termino.setObjectName(u"data_p_termino")
        self.data_p_termino.setCalendarPopup(True)
        self.splitter_5.addWidget(self.data_p_termino)
        self.splitter_6 = QSplitter(self.page_inserir)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setGeometry(QRect(20, 340, 231, 20))
        self.splitter_6.setMinimumSize(QSize(0, 20))
        self.splitter_6.setOrientation(Qt.Horizontal)
        self.label_7 = QLabel(self.splitter_6)
        self.label_7.setObjectName(u"label_7")
        self.splitter_6.addWidget(self.label_7)
        self.date_p_inicio = QDateEdit(self.splitter_6)
        self.date_p_inicio.setObjectName(u"date_p_inicio")
        self.date_p_inicio.setCalendarPopup(True)
        self.splitter_6.addWidget(self.date_p_inicio)
        self.pages.addWidget(self.page_inserir)
        self.page_editar = QWidget()
        self.page_editar.setObjectName(u"page_editar")
        self.log_alt = QTextBrowser(self.page_editar)
        self.log_alt.setObjectName(u"log_alt")
        self.log_alt.setGeometry(QRect(510, 20, 311, 421))
        self.label_14 = QLabel(self.page_editar)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 20, 201, 31))
        font1 = QFont()
        font1.setPointSize(20)
        self.label_14.setFont(font1)
        self.combo_select_alt = QComboBox(self.page_editar)
        self.combo_select_alt.setObjectName(u"combo_select_alt")
        self.combo_select_alt.setGeometry(QRect(200, 80, 201, 21))
        self.label_19 = QLabel(self.page_editar)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 420, 261, 21))
        self.splitter_14 = QSplitter(self.page_editar)
        self.splitter_14.setObjectName(u"splitter_14")
        self.splitter_14.setGeometry(QRect(10, 310, 141, 41))
        self.splitter_14.setOrientation(Qt.Vertical)
        self.label_20 = QLabel(self.splitter_14)
        self.label_20.setObjectName(u"label_20")
        self.splitter_14.addWidget(self.label_20)
        self.input_p_n_func_alt = QLineEdit(self.splitter_14)
        self.input_p_n_func_alt.setObjectName(u"input_p_n_func_alt")
        self.splitter_14.addWidget(self.input_p_n_func_alt)
        self.rbtn_f_alt = QRadioButton(self.page_editar)
        self.rbtn_f_alt.setObjectName(u"rbtn_f_alt")
        self.rbtn_f_alt.setGeometry(QRect(20, 80, 82, 17))
        self.rbtn_p_alt = QRadioButton(self.page_editar)
        self.rbtn_p_alt.setObjectName(u"rbtn_p_alt")
        self.rbtn_p_alt.setGeometry(QRect(130, 80, 82, 17))
        self.btn_rm_alt = QPushButton(self.page_editar)
        self.btn_rm_alt.setObjectName(u"btn_rm_alt")
        self.btn_rm_alt.setGeometry(QRect(410, 80, 75, 23))
        self.input_f_nome_alt = QLineEdit(self.page_editar)
        self.input_f_nome_alt.setObjectName(u"input_f_nome_alt")
        self.input_f_nome_alt.setGeometry(QRect(50, 160, 301, 20))
        self.input_f_nome_alt.setReadOnly(True)
        self.input_f_salario_alt = QLineEdit(self.page_editar)
        self.input_f_salario_alt.setObjectName(u"input_f_salario_alt")
        self.input_f_salario_alt.setGeometry(QRect(190, 210, 161, 20))
        self.output_f_n_func_alt = QLineEdit(self.page_editar)
        self.output_f_n_func_alt.setObjectName(u"output_f_n_func_alt")
        self.output_f_n_func_alt.setGeometry(QRect(10, 210, 161, 20))
        self.label_22 = QLabel(self.page_editar)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 230, 91, 31))
        font2 = QFont()
        font2.setPointSize(16)
        self.label_22.setFont(font2)
        self.label_23 = QLabel(self.page_editar)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(190, 190, 81, 16))
        self.label_24 = QLabel(self.page_editar)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 190, 171, 16))
        self.label_25 = QLabel(self.page_editar)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 120, 121, 31))
        self.label_25.setFont(font2)
        self.label_26 = QLabel(self.page_editar)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 160, 31, 16))
        self.output_p_nome_alt = QLineEdit(self.page_editar)
        self.output_p_nome_alt.setObjectName(u"output_p_nome_alt")
        self.output_p_nome_alt.setGeometry(QRect(10, 280, 341, 20))
        self.output_p_nome_alt.setReadOnly(True)
        self.btn_f_alterar = QPushButton(self.page_editar)
        self.btn_f_alterar.setObjectName(u"btn_f_alterar")
        self.btn_f_alterar.setGeometry(QRect(380, 160, 101, 71))
        self.btn_p_alterar = QPushButton(self.page_editar)
        self.btn_p_alterar.setObjectName(u"btn_p_alterar")
        self.btn_p_alterar.setGeometry(QRect(380, 360, 101, 71))
        self.label_29 = QLabel(self.page_editar)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(410, 60, 81, 16))
        self.label_16 = QLabel(self.page_editar)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 370, 55, 16))
        self.date_p_inicio_alt = QDateEdit(self.page_editar)
        self.date_p_inicio_alt.setObjectName(u"date_p_inicio_alt")
        self.date_p_inicio_alt.setGeometry(QRect(120, 370, 121, 20))
        self.date_p_inicio_alt.setCalendarPopup(True)
        self.label_15 = QLabel(self.page_editar)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 400, 68, 16))
        self.data_p_termino_alt = QDateEdit(self.page_editar)
        self.data_p_termino_alt.setObjectName(u"data_p_termino_alt")
        self.data_p_termino_alt.setGeometry(QRect(120, 400, 121, 20))
        self.data_p_termino_alt.setCalendarPopup(True)
        self.label_21 = QLabel(self.page_editar)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 260, 111, 16))
        self.label_17 = QLabel(self.page_editar)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(380, 310, 120, 16))
        self.input_p_meses_alt = QLineEdit(self.page_editar)
        self.input_p_meses_alt.setObjectName(u"input_p_meses_alt")
        self.input_p_meses_alt.setGeometry(QRect(380, 329, 101, 20))
        self.input_p_valor_est_alt = QLineEdit(self.page_editar)
        self.input_p_valor_est_alt.setObjectName(u"input_p_valor_est_alt")
        self.input_p_valor_est_alt.setGeometry(QRect(160, 329, 191, 20))
        self.label_18 = QLabel(self.page_editar)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(160, 310, 74, 16))
        self.pages.addWidget(self.page_editar)
        self.page_buscas = QWidget()
        self.page_buscas.setObjectName(u"page_buscas")
        self.table_busca = QTreeWidget(self.page_buscas)
        self.table_busca.setObjectName(u"table_busca")
        self.table_busca.setGeometry(QRect(10, 150, 801, 291))
        self.label_27 = QLabel(self.page_buscas)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(370, 0, 91, 31))
        self.label_27.setFont(font1)
        self.pushButton = QPushButton(self.page_buscas)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(30, 50, 131, 61))
        self.pushButton_5 = QPushButton(self.page_buscas)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(680, 80, 101, 51))
        self.label_28 = QLabel(self.page_buscas)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(680, 30, 101, 16))
        self.lineEdit = QLineEdit(self.page_buscas)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(680, 50, 101, 20))
        self.pushButton_2 = QPushButton(self.page_buscas)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(190, 50, 131, 61))
        self.pushButton_3 = QPushButton(self.page_buscas)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(350, 50, 131, 61))
        self.pushButton_4 = QPushButton(self.page_buscas)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(510, 50, 131, 61))
        self.pages.addWidget(self.page_buscas)
        self.btn_tela_inserir = QPushButton(self.centralwidget)
        self.btn_tela_inserir.setObjectName(u"btn_tela_inserir")
        self.btn_tela_inserir.setGeometry(QRect(10, 10, 131, 31))
        self.btn_tela_alterar = QPushButton(self.centralwidget)
        self.btn_tela_alterar.setObjectName(u"btn_tela_alterar")
        self.btn_tela_alterar.setGeometry(QRect(160, 10, 131, 31))
        self.btn_tela_buscar = QPushButton(self.centralwidget)
        self.btn_tela_buscar.setObjectName(u"btn_tela_buscar")
        self.btn_tela_buscar.setGeometry(QRect(310, 10, 131, 31))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 850, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.pages.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Funcion\u00e1rios", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Projetos", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Nome:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"(Caso esteja em andamento, mantenha 01/01/2000)", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Tempo estimado(meses):", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Valor estimado:", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Funcion\u00e1rio respons\u00e1vel:", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Resultado das opera\u00e7\u00f5es:", None))
        self.btn_inserir_f.setText(QCoreApplication.translate("MainWindow", u"Inserir", None))
        self.btn_p_inserir.setText(QCoreApplication.translate("MainWindow", u"Inserir", None))
        self.btn_limpar_p_inserir.setText(QCoreApplication.translate("MainWindow", u"Limpar", None))
        self.btn_limpar_f_inserir.setText(QCoreApplication.translate("MainWindow", u"Limpar", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Nome", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Sal\u00e1rio:", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"N\u00famero Funcional (Opcional):", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Data T\u00e9rmino:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Data In\u00edcio:", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Editar / Remover", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"(Caso esteja em andamento, mantenha 01/01/2000)", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Funcion\u00e1rio respons\u00e1vel:", None))
        self.rbtn_f_alt.setText(QCoreApplication.translate("MainWindow", u"Funcion\u00e1rio", None))
        self.rbtn_p_alt.setText(QCoreApplication.translate("MainWindow", u"Projeto", None))
        self.btn_rm_alt.setText(QCoreApplication.translate("MainWindow", u"Remover", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Projeto", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Sal\u00e1rio:", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"N\u00famero Funcional (N\u00e3o edit\u00e1vel):", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Funcion\u00e1rio", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Nome:", None))
        self.btn_f_alterar.setText(QCoreApplication.translate("MainWindow", u"Alterar", None))
        self.btn_p_alterar.setText(QCoreApplication.translate("MainWindow", u"Alterar", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Deseja remover?", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Data In\u00edcio:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Data T\u00e9rmino:", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Nome (N\u00e3o edit\u00e1vel):", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Tempo estimado(meses):", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Valor estimado:", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Buscas", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Listar Funcion\u00e1rios\n"
"(Sal\u00e1rio decrescente)", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Buscar Endere\u00e7o\n"
" de mem\u00f3ria", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"N\u00famero Funcion\u00e1rio:", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Listar Funcion\u00e1rios\n"
"com projetos\n"
"em andamento\n"
"atribu\u00eddos", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Listar projetos\n"
"de mais de R$500k\n"
"em andamento", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Listar projetos\n"
"atrasados ou\n"
"terminados com atraso", None))
        self.btn_tela_inserir.setText(QCoreApplication.translate("MainWindow", u"INSERIR DADOS", None))
        self.btn_tela_alterar.setText(QCoreApplication.translate("MainWindow", u"EDITAR/REMOVER", None))
        self.btn_tela_buscar.setText(QCoreApplication.translate("MainWindow", u"BUSCAS", None))
    # retranslateUi

